# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaMatMult <- function(A, B) {
    .Call('_MRCD_armaMatMult', PACKAGE = 'MRCD', A, B)
}

eigenMatMult <- function(A, B) {
    .Call('_MRCD_eigenMatMult', PACKAGE = 'MRCD', A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call('_MRCD_eigenMapMatMult', PACKAGE = 'MRCD', A, B)
}

